In [1]:
import numpy as np
import cv2


# Q1: implement a linear regression model
data row1 > header 
 ### 1: data preprocessing 
       #i. apply to_add array to data where element 1 added to row 1 , element 2 added to row 2 and so on 
       #ii.apply to_Mult array to the data row by to 
 ### 2: get the prediction values using the hyposis function weight array (regression_model)

In [2]:
Data= np.array([[1000,1001,1002,1003],
                [8,18,28,38],
               [16,26,36,46],
               [4,14,24,44]],dtype="int64")

to_add=np.array([2,4,6])
to_mult=np.array([10,100,1000,1000])
regression_model=np.array([2,4,6,8])

In [3]:
##step1 print dataset without header row
Data_without_header=Data[1:,:]
print(Data_without_header)

[[ 8 18 28 38]
 [16 26 36 46]
 [ 4 14 24 44]]


In [4]:
###step2 i. to_Add
to_add=to_add.reshape(3,1)
to_Add=Data_without_header+to_add
print(to_Add)

[[10 20 30 40]
 [20 30 40 50]
 [10 20 30 50]]


In [5]:
##step3 ii. to_MUlt
to_mul=to_mult.reshape(4,1)
to_MUlt=to_Add*to_mult
print(to_MUlt)

[[  100  2000 30000 40000]
 [  200  3000 40000 50000]
 [  100  2000 30000 50000]]


In [6]:
###step4 prediction results
regression_model=regression_model.reshape(4,1)
results=to_MUlt@regression_model
print(results)

[[508200]
 [652400]
 [588200]]


In [7]:
!pip install opencv-python

# Q2. Transformation

### apply crop , rotation  to the image 

#1: convert image from  BGR scale to Gray , Red ,Green & Blue scale
#2: crop the right  half
#3: crop the right bottom quarter
#4: zoom in by remove the quarter border from all sides 
#5: flip on x-axis 
#6: flip on y-axis 

In [8]:
image=cv2.imread("image.jpg") ### in_BGR
cv2.imshow("original_image",image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
## step1 print image data 
print(image[:,:,:])


[[[246 236 236]
  [247 237 237]
  [248 238 238]
  ...
  [250 242 235]
  [250 242 235]
  [250 242 235]]

 [[246 236 236]
  [246 236 236]
  [247 237 237]
  ...
  [249 241 234]
  [249 241 234]
  [249 241 234]]

 [[245 235 235]
  [246 236 236]
  [247 237 237]
  ...
  [249 241 234]
  [249 241 234]
  [249 241 234]]

 ...

 [[ 23  33  16]
  [ 44  54  37]
  [ 65  72  57]
  ...
  [ 19  61  68]
  [ 19  61  68]
  [ 19  61  68]]

 [[ 34  46  28]
  [ 57  69  51]
  [ 71  82  66]
  ...
  [ 11  60  70]
  [ 11  60  70]
  [ 11  60  70]]

 [[ 71  85  67]
  [ 94 108  90]
  [103 116 100]
  ...
  [ 10  64  75]
  [ 10  64  75]
  [ 10  64  75]]]


In [10]:
## step2 print image shape
print(image.shape)

(183, 276, 3)


In [11]:
## step3  get the value of lx ,ly 
lx=image.shape[0]
ly=image.shape[1]



In [12]:
### step4 image in gray scale 
cv2.imshow("Gray scale",image[:,:,1])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
### step 5 image in Blue scale 
blue_channel = image[:,:,0]
blue_img = np.zeros(image.shape)
blue_img[:,:,0]=blue_channel
cv2.imshow("Blue Scale",blue_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
### step 6 image in red scale 
red_channel = image[:,:,2]
red_img = np.zeros(image.shape)
red_img[:,:,2]=red_channel
cv2.imshow("Red Scale",red_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
### step 7 image in Green scale 
green_channel = image[:,:,1]
green_img = np.zeros(image.shape)
green_img[:,:,1]=red_channel
cv2.imshow("Green scale",green_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
# step 8 crop the right half
ly_half=ly//2
cv2.imshow("original_image",image[:,:,:])
cv2.imshow(" right half",image[:,ly_half:,:])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [31]:
## step 9 crop the right bottom quarter

cv2.imshow("gray",image[:,:,:])
cv2.imshow(" right bottom quarter",image[lx//2:,ly//2:,:])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [32]:
## step 10 remove the quarter border from all sides 
cv2.imshow("original_image",image[:,:,:])
cv2.imshow(" zoom in ",image[lx//4:3*lx//4,ly//4:3*ly//4,:])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
## step 11 flip on x-axis 
print(image.shape)
cv2.imshow("original_image",image[:,:,:])
cv2.imshow(" flip the image in x axis ",image[lx:0:-1,:,:])
cv2.waitKey(0)
cv2.destroyAllWindows()

(183, 276, 3)


In [20]:
## step 12 flip on y-axis
cv2.imshow("original_image",image[:,:,:])
cv2.imshow(" flip the image in y axis ",image[:,ly:0:-1,:])
cv2.waitKey(0)
cv2.destroyAllWindows()

## Q3  Write a program to broadcast on different shapes of arrays where p(3,3) + q(3)

- p >> [[0, 0, 0],[1, 2, 3],[4, 5, 6]]
- q >> [10, 11, 12]

In [21]:
p=np.array([[0, 0, 0],[1, 2, 3],[4, 5, 6]])
q=np.array([10, 11, 12])
print(p+q)

[[10 11 12]
 [11 13 15]
 [14 16 18]]


## Q4 Write a NumPy program to make an array immutable 

In [22]:
array_of_2 = np.full((3, 5), 2)
array_of_2.flags.writeable=False 
print(array_of_2)


[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


## Q5 Write a NumPy program to create a new array of 3*5, filled with 2

In [23]:
array_of_2 = np.full((3, 5), 2)
print(array_of_2)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


## Q6 Write a NumPy program to get the number of nonzero elements in an array

- array = [[0, 10, 20], [20, 0, 40]]

In [24]:
array=np.array([[0, 10, 20], [20, 0, 40]])
print(np.count_nonzero(array))

4


## Q7 Write a NumPy program to get the minimum and maximum value of an array along the second axis

- create array 2x2 contains data from 0 to 3 

In [25]:
array=np.arange(4).reshape((2, 2))
print(np.min(array))
print(np.max(array))


0
3


## Q8  Write a NumPy program to compute the mean, median,standard deviation, and variance of a given array 

- array = [0 4 2 1 3 5]

In [26]:

array = np.array([0, 4 ,2, 1, 3 ,5])
print("mean",np.mean(array))
print("median",np.median(array))
print("standard deviation",np.std(array))
print("variance",np.var(array))



mean 2.5
median 2.5
standard deviation 1.707825127659933
variance 2.9166666666666665
